### ISSUE TITLE
Code and pre-trained model release

### ISSUE THREAD

**Issue by ioalzx** [Abdullah-Abuolaim/multi-task-defocus-deblurring-dual-pixel-nimat#8]
Hi, I am very excited about the resulting effects and wondering when will you release the code and pre-trained model.

**Comment by Abdullah-Abuolaim** [comment]
Hello there,

Thanks for your interest in this work. I have uploaded the code along with the trained models. Now, you can go ahead to try out the new image motion i.e., the NIMAT effect :-)

Best,
Abdullah
